/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

/**
 *
 * @author ivan1
 */
public class TCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TCalculadora
     */
    public TCalculadora() {
        initComponents();
    }
    
    double valorUm, valorDois, mrc;
    String operacao;
    
    public void audio (String somCalculadora) {
        URL url = getClass().getResource(somCalculadora+".wav");
        AudioClip audio = Applet.newAudioClip(url);
        audio.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        zeroBt = new javax.swing.JButton();
        pontoBt = new javax.swing.JButton();
        umBt = new javax.swing.JButton();
        doisBt = new javax.swing.JButton();
        tresBt = new javax.swing.JButton();
        quatroBt = new javax.swing.JButton();
        cincoBt = new javax.swing.JButton();
        seisBt = new javax.swing.JButton();
        seteBt = new javax.swing.JButton();
        oitoBt = new javax.swing.JButton();
        noveBt = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        raizBt = new javax.swing.JToggleButton();
        divBt = new javax.swing.JButton();
        igualBt = new javax.swing.JButton();
        restoBt = new javax.swing.JButton();
        vezesBt = new javax.swing.JButton();
        menosBt = new javax.swing.JButton();
        maisBt = new javax.swing.JButton();
        mMenosBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mMaisBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mrcBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        limparBt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fieldConta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Off");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        zeroBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        zeroBt.setText("0");
        zeroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtActionPerformed(evt);
            }
        });

        pontoBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pontoBt.setText("●");
        pontoBt.setPreferredSize(new java.awt.Dimension(72, 22));
        pontoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoBtActionPerformed(evt);
            }
        });

        umBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        umBt.setText("1");
        umBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umBtActionPerformed(evt);
            }
        });

        doisBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        doisBt.setText("2");
        doisBt.setPreferredSize(new java.awt.Dimension(54, 54));
        doisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisBtActionPerformed(evt);
            }
        });

        tresBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tresBt.setText("3");
        tresBt.setPreferredSize(new java.awt.Dimension(54, 54));
        tresBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBtActionPerformed(evt);
            }
        });

        quatroBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quatroBt.setText("4");
        quatroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroBtActionPerformed(evt);
            }
        });

        cincoBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cincoBt.setText("5");
        cincoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBtActionPerformed(evt);
                som(evt);
            }
        });

        seisBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        seisBt.setText("6");
        seisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtActionPerformed(evt);
            }
        });

        seteBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        seteBt.setText("7");
        seteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteBtActionPerformed(evt);
            }
        });

        oitoBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        oitoBt.setText("8");
        oitoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoBtActionPerformed(evt);
            }
        });

        noveBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        noveBt.setText("9");
        noveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveBtActionPerformed(evt);
            }
        });

        jButton13.setText("🔊");

        raizBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        raizBt.setText("√");
        raizBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizBtActionPerformed(evt);
            }
        });

        divBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        divBt.setText("÷");
        divBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtActionPerformed(evt);
            }
        });

        igualBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        igualBt.setText("=");
        igualBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBtActionPerformed(evt);
            }
        });

        restoBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        restoBt.setText("%");
        restoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoBtActionPerformed(evt);
            }
        });

        vezesBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        vezesBt.setText("x");
        vezesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezesBtActionPerformed(evt);
            }
        });

        menosBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        menosBt.setText("-");
        menosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosBtActionPerformed(evt);
            }
        });

        maisBt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        maisBt.setText("+");
        maisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisBtActionPerformed(evt);
            }
        });

        mMenosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenosBtActionPerformed(evt);
            }
        });

        jLabel1.setText("M-");

        mMaisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMaisBtActionPerformed(evt);
            }
        });

        jLabel2.setText("M+");

        mrcBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrcBtActionPerformed(evt);
            }
        });

        jLabel3.setText("MRC");

        limparBt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limparBt.setText("C");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limparBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        limparBt.getAccessibleContext().setAccessibleName("C");

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 3, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tec Calculator");

        fieldConta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(zeroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pontoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(31, 31, 31))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(seteBt, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                                    .addComponent(quatroBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(umBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cincoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(doisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(oitoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(raizBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mrcBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addComponent(mMaisBt))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel1)
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(noveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(vezesBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(menosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(igualBt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(18, 18, 18)
                                                            .addComponent(maisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(mMenosBt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                            .addComponent(restoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton1))))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fieldConta)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(fieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mMenosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrcBt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mMaisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raizBt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seteBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oitoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vezesBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noveBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quatroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cincoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(umBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zeroBt, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(igualBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pontoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(maisBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cincoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"5");
    }//GEN-LAST:event_cincoBtActionPerformed

    private void zeroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"0");
    }//GEN-LAST:event_zeroBtActionPerformed

    private void umBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"1");
    }//GEN-LAST:event_umBtActionPerformed

    private void doisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"2");
    }//GEN-LAST:event_doisBtActionPerformed

    private void tresBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"3");
    }//GEN-LAST:event_tresBtActionPerformed

    private void quatroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"4");
    }//GEN-LAST:event_quatroBtActionPerformed

    private void seisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"6");
    }//GEN-LAST:event_seisBtActionPerformed

    private void seteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"7");
    }//GEN-LAST:event_seteBtActionPerformed

    private void oitoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"8");
    }//GEN-LAST:event_oitoBtActionPerformed

    private void noveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveBtActionPerformed
        fieldConta.setText(fieldConta.getText()+"9");
    }//GEN-LAST:event_noveBtActionPerformed

    private void pontoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoBtActionPerformed
        fieldConta.setText(fieldConta.getText()+".");
    }//GEN-LAST:event_pontoBtActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        fieldConta.setText("");
    }//GEN-LAST:event_limparBtActionPerformed

    private void maisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisBtActionPerformed
        valorUm = Double.parseDouble(fieldConta.getText());
        operacao = "soma";
        fieldConta.setText("");
    }//GEN-LAST:event_maisBtActionPerformed

    private void igualBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBtActionPerformed
        valorDois = Double.parseDouble(fieldConta.getText());
        if(operacao.equals("soma")) {
           fieldConta.setText(String.valueOf(valorUm+valorDois));
        }
        if(operacao.equals("subtracao")) {
            fieldConta.setText(String.valueOf(valorUm-valorDois));
        }
        if(operacao.equals("multiplicacao")) {
            fieldConta.setText(String.valueOf(valorUm*valorDois));
        }
        if(operacao.equals("divisao")) {
            fieldConta.setText(String.valueOf(valorUm/valorDois));
        }
    }//GEN-LAST:event_igualBtActionPerformed

    private void menosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosBtActionPerformed
        valorUm = Double.parseDouble(fieldConta.getText());
        operacao = "subtracao";
        fieldConta.setText("");
    }//GEN-LAST:event_menosBtActionPerformed

    private void vezesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezesBtActionPerformed
        valorUm = Double.parseDouble(fieldConta.getText());
        operacao = "multiplicacao";
        fieldConta.setText("");
    }//GEN-LAST:event_vezesBtActionPerformed

    private void divBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtActionPerformed
        valorUm = Double.parseDouble(fieldConta.getText());
        operacao = "divisao";
        fieldConta.setText("");
    }//GEN-LAST:event_divBtActionPerformed

    private void mrcBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrcBtActionPerformed
        fieldConta.setText(String.valueOf(mrc));
    }//GEN-LAST:event_mrcBtActionPerformed

    private void mMenosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenosBtActionPerformed
        mrc = 0;
    }//GEN-LAST:event_mMenosBtActionPerformed

    private void mMaisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMaisBtActionPerformed
        mrc = Double.parseDouble(fieldConta.getText());
    }//GEN-LAST:event_mMaisBtActionPerformed

    private void raizBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizBtActionPerformed
        valorUm = Double.parseDouble(fieldConta.getText());
        fieldConta.setText(String.valueOf(Math.sqrt(valorUm)));
    }//GEN-LAST:event_raizBtActionPerformed

    private void restoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoBtActionPerformed
        if(operacao.equals("divisao")) {
            fieldConta.setText(String.valueOf(valorUm % valorDois));
        }
    }//GEN-LAST:event_restoBtActionPerformed

    private void som(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som
        // TODO add your handling code here:
    }//GEN-LAST:event_som

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincoBt;
    private javax.swing.JButton divBt;
    private javax.swing.JButton doisBt;
    private javax.swing.JTextField fieldConta;
    private javax.swing.JButton igualBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limparBt;
    private javax.swing.JButton mMaisBt;
    private javax.swing.JButton mMenosBt;
    private javax.swing.JButton maisBt;
    private javax.swing.JButton menosBt;
    private javax.swing.JButton mrcBt;
    private javax.swing.JButton noveBt;
    private javax.swing.JButton oitoBt;
    private javax.swing.JButton pontoBt;
    private javax.swing.JButton quatroBt;
    private javax.swing.JToggleButton raizBt;
    private javax.swing.JButton restoBt;
    private javax.swing.JButton seisBt;
    private javax.swing.JButton seteBt;
    private javax.swing.JButton tresBt;
    private javax.swing.JButton umBt;
    private javax.swing.JButton vezesBt;
    private javax.swing.JButton zeroBt;
    // End of variables declaration//GEN-END:variables
}
